spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:admin}:${MONGO_INITDB_ROOT_PASSWORD:admin}@localhost:${MONGO_PORT:27017}/${MONGO_INITDB_DATABASE:payment_db}?authSource=admin
  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT:9092}